image: node:latest

# before_script:
#   - /bin/bash ./setup_ssh.sh

bump_me_ooooooon:
  script:
    - npm install
    - node ./createLanguageFallbacks.js
    - npm run test
    - npm run fix:prettier
    - /bin/bash ./bump_version.sh
    - git remote set-url origin https://kissu:8E65UiMjehAcWQEY9faT@gitlab.com/kissu/test_weblate.git
    - git push origin-master
