image: ilyasemenov/gitlab-ci-git-push
  # node:latest

# before_script:
#   - /bin/bash ./setup_ssh.sh

bump_me_ooooooon:
  script:
    # - npm install
    # - node ./createLanguageFallbacks.js
    # - npm run test
    # - npm run fix:prettier
    # - /bin/bash ./bump_version.sh
    # - echo 'Setup SSH'
    # - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    # - eval $(ssh-agent -s)
    # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    # - mkdir -p ~/.ssh
    # - chmod 700 ~/.ssh
    - git config --global user.name TastyCI
    - git config --global user.email hello@kissu.io
    # - echo 'everything is setup properly'
    # - git remote add origin git@gitlab.com:kissu/test_weblate.git
    # - git push --tags origin master
    # - touch git-push.md
    # - git-push kissu@git@gitlab.com:kissu/test_weblate.git
