image: node:latest

# before_script:
#   - /bin/bash ./setup_ssh.sh

bump_me_ooooooon:
  script:
    - npm install
    - node ./createLanguageFallbacks.js
    - npm run test
    - npm run fix:prettier
    - /bin/bash ./bump_version.sh
    - git config --global user.name TastyCI
    - git config --global user.email hello@kissu.io
    - git remote add origin git@gitlab.com:kissu/test_weblate.git
    - git push --tags origin master
